### PR TITLE
Compatibility with safari < 14

### PR DESCRIPTION
**Pull request by kthai-nr**
Updating initial PR set by #57 by @stevesum with suggested changes in order to be compatible with iOS < 14.

### CODE REVIEW

**Comment by kthai-nr** [comment]
@stevesum If you could review and sign the CLA, we will be pushing this fix on our next release soon

**Comment by stevesum** [comment]
@kthai-nr signed, and I agree with your changes. My fault, I forget to follow back static variables.

**Review by stevesum — APPROVED** [review]
You are right. My fault, I not followed back the static variables.

**Review by stevesum — APPROVED** [review]

**Review by stevesum — APPROVED** [review]

**Review by ndesai-newrelic — APPROVED** [review]

**Comment by kthai-nr** [comment]
We appreciate the help!

**Pull request merged**
